# Generated by Django 4.0 on 2022-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_book_reviews_average_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-reviews_average', '-reviews_count']},
        ),
        migrations.AlterField(
            model_name='book',
            name='reviews_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviews_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
